# Generated by Django 5.0.2 on 2024-08-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plots", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plot",
            name="main_image",
            field=models.ImageField(
                blank=True, default="default_plot.png", upload_to="plot_images"
            ),
        ),
    ]
